### ISSUE TITLE
Dependency Installation Versioning

### ISSUE THREAD

**Issue by hironroy** [AutoViML/AutoViz#1]
At workshop, we encountered a couple of issues with versions of deps. The following versions and procedure allow for the demo notebook to run.

```
# in a brand new conda env
conda install jupyter pandas=0.23 matplotlib=3.0.2 seaborn=0.9 xlrd=1.2.0 scikit-learn
pip install xgboost
```

**Comment by AutoViML** [comment]
Thanks Hiron this is something we should package and turn into a pip install. Otherwise it will be a problem for others to install and run.

**Comment by hironroy** [comment]
PR for latest dep compatibility: #2  -- Doesn't get us all the way to a pip install, but is a step in the right direction.

**Comment by AutoViML** [comment]
thanks have accepted all your changes
