### ISSUE TITLE
ImportError: cannot import name 'rx' from 'param'

### ISSUE THREAD

**Issue by CorneliusFranken** [AutoViML/AutoViz#100]
Python version: 3.9
**Environment**
Environment set up with latest requirements.txt, plus following packages:
ipykernel
pandas
openpyxl

**Error code line**
from autoviz import AutoViz_Class

**Error produced:**
{
	"name": "ImportError",
	"message": "cannot import name 'rx' from 'param' (c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\param\\__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
x:\\CJF\\python\\chainladder\\Sandpit_cjf\\Infrasure_EDA_Autoviz.ipynb Cell 7 line 2
      <a href='vscode-notebook-cell:/x%3A/CJF/python/chainladder/Sandpit_cjf/Infrasure_EDA_Autoviz.ipynb#W6sZmlsZQ%3D%3D?line=0'>1</a> # load the autoviz
----> <a href='vscode-notebook-cell:/x%3A/CJF/python/chainladder/Sandpit_cjf/Infrasure_EDA_Autoviz.ipynb#W6sZmlsZQ%3D%3D?line=1'>2</a> from autoviz import AutoViz_Class

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\autoviz\\__init__.py:3
      1 name = \"autoviz\"
      2 from .__version__ import __version__, __holo_version__
----> 3 from .AutoViz_Class import AutoViz_Class
      4 from .AutoViz_Class import data_cleaning_suggestions
      5 from .AutoViz_Class import FixDQ

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\autoviz\\AutoViz_Class.py:61
     59 from sklearn.model_selection import train_test_split
     60 ##########################################################################################
---> 61 from autoviz.AutoViz_Holo import AutoViz_Holo
     62 from autoviz.AutoViz_Utils import save_image_data, save_html_data, analyze_problem_type, draw_pivot_tables, draw_scatters
     63 from autoviz.AutoViz_Utils import draw_pair_scatters, plot_fast_average_num_by_cat, draw_barplots, draw_heatmap

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\autoviz\\AutoViz_Holo.py:5
      3 import pandas as pd
      4 ############# Import from autoviz.AutoViz_Class the following libraries #######
----> 5 from autoviz.AutoViz_Utils import *
      6 ##############   make sure you use: conda install -c pyviz hvplot ###############
      7 import hvplot.pandas  # noqa

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\autoviz\\AutoViz_Utils.py:61
     59 from sklearn.model_selection import train_test_split
     60 ######## This is where we import HoloViews related libraries  #########
---> 61 import hvplot.pandas
     62 import holoviews as hv
     63 from holoviews import opts

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\hvplot\\__init__.py:8
      5 import textwrap
      7 import param
----> 8 import holoviews as _hv
     10 from holoviews import Store
     12 from .converter import HoloViewsConverter

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\holoviews\\__init__.py:12
      8 __version__ = str(param.version.Version(fpath=__file__, archive_commit=\"$Format:%h$\",
      9                                         reponame=\"holoviews\"))
     11 from . import util                                       # noqa (API import)
---> 12 from .annotators import annotate                         # noqa (API import)
     13 from .core import archive, config                        # noqa (API import)
     14 from .core.boundingregion import BoundingBox             # noqa (API import)

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\holoviews\\annotators.py:10
      6 from inspect import getmro
      8 import param
---> 10 from panel.pane import PaneBase
     11 from panel.layout import Row, Tabs
     12 from panel.util import param_name

File c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\panel\\__init__.py:48
      1 \"\"\"
      2 Panel is a high level app and dashboarding framework
      3 ====================================================
   (...)
     46 https://panel.holoviz.org/getting_started/index.html
     47 \"\"\"
---> 48 from param import rx
     50 from . import chat  # noqa
     51 from . import layout  # noqa

ImportError: cannot import name 'rx' from 'param' (c:\\EnvPython\\EDA\\venv_EDA_Autoviz\\lib\\site-packages\\param\\__init__.py)"
}

**Comment by AutoViML** [comment]
Hi @CorneliusFranken 👍 
Can you please check online if this is an error due to various hvplot versions? I am sorry I can't fix these kinds of issues.
