### ISSUE TITLE
Inconsistent performance

### ISSUE THREAD

**Issue by ArijitSinghEDA** [AutoViML/AutoViz#104]
I have a dataset with 6439 rows and 28 columns(5 string columns,1 datetime column,3 integers,19 float columns)

These are the installed requirements for `python 3.8.18`

```
bokeh 2.4.3
holoviews 1.14.9
hvplot 0.7.3
panel 0.14.4
```

When trying to create autoviz charts then it is creating only `data quality report`, `displots_nums.html`, and `pair_scatters.html` charts and gives the following error

```
underflow encountered in true_divide
```

when taking only 2000 rows of the same dataset, everything works fine.

**Comment by AutoViML** [comment]
Can you please attach a screenshot of the entire errror report? I can try to see where the error is happening and try to fix it?ThanksAuto Vimal
    On Monday, February 12, 2024 at 12:10:27 AM EST, ArijitSinghEDA ***@***.***> wrote:  
 
 


I have a dataset with 6439 rows and 28 columns(5 string columns,1 datetime column,3 integers,19 float columns)

These are the installed requirements for python 3.8.18
bokeh 2.4.3
holoviews 1.14.9
hvplot 0.7.3
panel 0.14.4

When trying to create autoviz charts then it is creating only data quality report, displots_nums.html, and pair_scatters.html charts and gives the following error
underflow encountered in true_divide

when taking only 2000 rows of the same dataset, everything works fine.

**Comment by ArijitSinghEDA** [comment]
![image](https://github.com/AutoViML/AutoViz/assets/132063833/924ff681-8d8d-4ccc-bda1-3e333d02dc0f)

**Comment by AutoViML** [comment]
Hi I think I found the problem and fixed it. Please upgrade to the latest version of autoviz by:`pip install autoviz --upgrade`
ThanksAuto Vimal

    On Tuesday, February 13, 2024 at 12:25:42 AM EST, ArijitSinghEDA ***@***.***> wrote:  
 
 


image.png (view on web)

**Comment by ArijitSinghEDA** [comment]
I will try and let you know. Thank you
