### ISSUE TITLE
Increase dependency for holoviews

### ISSUE THREAD

**Issue by czFIRE** [AutoViML/AutoViz#106]
The problem is that the old holoviews package uses deprecated features of numpy - concretely I'm getting error with the type `np.bool` and it's deprecation in numpy version 1.20. Now we even have numpy version of 2.1 and thus the dependencies need to be updated.

**Comment by AutoViML** [comment]
Hi @czFIRE 
I have upgraded AutoViz to work with Python version 3.11 and 3.12 on Windows 👍
Please updgrade your AutoViz as follows
```
pip install autoviz --upgrade
```
If you see version 0.1.807, then you are in good shape
Let me know
Ram

**Comment by AutoViML** [comment]
Hi @czFIRE 
Sorry for the errors. I noticed that with pandas 2.0 and numpy >1.24 and newer python versions, the entire python ecosystem has gone for a toss. I am sorry to say but it is hitting open source developers like me hard. We now have to have different versions for different python versions. I have tried my best to maintain support for AutoViz in these trying times for python ecosystem. So please try to install directly from the github if possible to get the latest updates.

`pip install git+https://github.com/AutoViML/AutoViz.git --user`

For now, I have fixed your error 👍 

You can check it by upgrading to autoviz version 0.1.901 as follows
`pip install autoviz==0.1.901`

or 
`pip install autoviz --upgrade`

Thanks
AutoVimal
