### ISSUE TITLE
Bar Charts customization and skipping WordArt.

### ISSUE THREAD

**Issue by jackfood** [AutoViML/AutoViz#109]
![Bar_Plots](https://github.com/AutoViML/AutoViz/assets/11504716/99c25006-14ce-4780-b274-c6076afc1d3b)

1. Could I adjust the 'Counts' displayed in the bar plots based on selected variables, or can i manually input two variables to compare in bar chart for 'depVar'? The bar generated seems lacks meaningful insights.

```
from autoviz import AutoViz_Class
AV = AutoViz_Class()

filename = "C:\\Users\\gxu\\Desktop\\Book1.csv"
target_variable = "Administered Time"

dft = AV.AutoViz(
    filename,
    sep=",",
    depVar=target_variable,
    dfte=None,
    header=0,
    verbose=2,
    lowess=False,
    chart_format ='html',
    max_rows_analyzed=300000,
    max_cols_analyzed=30,
    save_plot_dir="C:\\Users\\gxu\\Desktop\\"
)
```

2. Also, is there a way to skip generating WordCloud?

3. for chartformat = 'server', some of the charts are too small, can i adjust the size of the chart?
![image](https://github.com/AutoViML/AutoViz/assets/11504716/d2c9fced-1b0b-4244-908b-1b41f8f71ba6)

Anyway, Great work on this Python tool for visualization! It's incredibly helpful and has saved me a lot of time in getting an overview. I'll definitely be checking back regularly for updates.

**Comment by AutoViML** [comment]
Hi @jackfood 👍 
Thank you for trying out AutoViz and providing your feedback. Though I wish I could do the changes you requested, these are very specific and I feel that they could be better done by Seaborn in one line of code by yourself. Instead, I want AutoViz to be a general purpose library to fit a lot of use cases. I think there are some errors in the charts that you have pointed out which I will fix when I get some time.
In the meantime, enjoy auto visualization!
Ram
