### ISSUE TITLE
Use black formatter

### ISSUE THREAD

**Issue by morenoh149** [AutoViML/AutoViz#13]
Would you welcome a PR adding black formatting to the project? https://github.com/psf/black

**Comment by AutoViML** [comment]
That will be awesome. please do.
Ram

**Comment by morenoh149** [comment]
ok here's how pandas uses it https://github.com/pandas-dev/pandas/blob/55ef668fc1cddd1bd214387d5b82e438c99b06ab/Makefile#L17 as an example

**Comment by AutoViML** [comment]
Look forward to the PR. Start with AutoViz.
Ram

**Comment by AutoViML** [comment]
Since nothing has been done by the commenter for last 2 years, closing this issue.
