### ISSUE TITLE
Project logo [help wanted]

### ISSUE THREAD

**Issue by morenoh149** [AutoViML/AutoViz#15]
If anyone with design sensibilities sees this. We are open to changing the project logo.

We like the pandas logo for example https://github.com/pandas-dev/pandas ![](https://camo.githubusercontent.com/5cb734f6fc37f645dc900e35559c60d91cc6b550/68747470733a2f2f6465762e70616e6461732e696f2f7374617469632f696d672f70616e6461732e737667)

**Comment by sanketghanmare** [comment]
hey hi, my name is Sanket. I can help you with this. Can you give me some more in-depth details about this?. My email address is sanketghanmare@gmail.com. Thank you

**Comment by sanketghanmare** [comment]
<img width="499" alt="Screen Shot 2020-07-25 at 7 55 20 PM" src="https://user-images.githubusercontent.com/24240931/88468422-665b1580-ceb1-11ea-9c28-c56745de79da.png">
<img width="499" alt="Screen Shot 2020-07-25 at 7 56 06 PM" src="https://user-images.githubusercontent.com/24240931/88468423-66f3ac00-ceb1-11ea-8075-672dfe1bc3ae.png">
<img width="498" alt="Screen Shot 2020-07-25 at 7 57 00 PM" src="https://user-images.githubusercontent.com/24240931/88468424-678c4280-ceb1-11ea-8cf5-48d560d0d8f6.png">
<img width="498" alt="Screen Shot 2020-07-25 at 7 57 13 PM" src="https://user-images.githubusercontent.com/24240931/88468425-678c4280-ceb1-11ea-8439-5762558cb763.png">
<img width="501" alt="Screen Shot 2020-07-25 at 7 57 24 PM" src="https://user-images.githubusercontent.com/24240931/88468426-678c4280-ceb1-11ea-8304-f991a969a2e2.png">
<img width="497" alt="Screen Shot 2020-07-25 at 7 57 45 PM" src="https://user-images.githubusercontent.com/24240931/88468427-678c4280-ceb1-11ea-87a6-8b316135f26b.png">

**Comment by sanketghanmare** [comment]
Let me know if you need more ideas or liked any one of the submitted above.
Best,
Sanket

**Comment by AutoViML** [comment]
Saket
I liked this
[image: image.png]
Can you spruce up the README page with this logo (prune it a bit to make it
smaller) and make the whole README page look nice?

If you have some skills in Markdown, modify the README page and then you
can submit a Pull Request with the logo  and I'll accept it.

That way, you'll be credited as a Contributor to this module. How does that
sound?
Thx
Ram

**Comment by sanketghanmare** [comment]
Hi Ram,
            I can only see the string of the image which you choose but not the actual image, Can you elaborate more on the logo you choose? After that, I will push the changes. Thank you.
Best,
Sanket

**Comment by AutoViML** [comment]
The image has a white background and an orange colored triangles like this
with AutoViML in black color - hope this helps.

**Comment by sanketghanmare** [comment]
hey cool I will add it
let me know the next steps

**Comment by AutoViML** [comment]
Just modify the Readme page on GitHub and submit a pull request. I’ll
accept it.
Thanks a lot
Ram

**Comment by AutoViML** [comment]
Sanket
I added your logo and your name as the creator of the logo - hope you like
it!
Thanks
Ram

**Comment by sanketghanmare** [comment]
Hi Ram,
            Greetings of the day. I planned to do this oncoming 10th
because the last day of my summer semester is the 9th of August and I
needed to submit my final Assignment before 10th. Thank you for handling it
on my behalf. If there are any more interesting tasks for which I can
contribute then please let me know. I will reply as soon as possible.

Best,
Sanket

**Comment by AutoViML** [comment]
Can you please create a similar logo for AutoViz after looking at the
product whenever you have some time after Aug 10th?
Thanks
Ram

**Comment by sanketghanmare** [comment]
Ya, sure I will do it. Do you want the exact same design? or something new

**Comment by AutoViML** [comment]
Something new - it should reflect something about visualization.
Ram

**Comment by sanketghanmare** [comment]
I will look into it and get back to you Ram.

**Comment by sanketghanmare** [comment]
<img width="500" alt="Screen Shot 2020-08-09 at 6 40 30 PM" src="https://user-images.githubusercontent.com/24240931/89743313-1c0c9380-da70-11ea-9058-b3b67225392e.png">
<img width="498" alt="Screen Shot 2020-08-09 at 6 40 18 PM" src="https://user-images.githubusercontent.com/24240931/89743314-1ca52a00-da70-11ea-8e30-5120721e0c50.png">
<img width="497" alt="Screen Shot 2020-08-09 at 6 39 44 PM" src="https://user-images.githubusercontent.com/24240931/89743315-1d3dc080-da70-11ea-99b6-99f48bbc5bb7.png">
<img width="499" alt="Screen Shot 2020-08-09 at 6 37 21 PM" src="https://user-images.githubusercontent.com/24240931/89743316-1d3dc080-da70-11ea-9c23-5d2e515b37f2.png">
<img width="498" alt="Screen Shot 2020-08-09 at 6 37 13 PM" src="https://user-images.githubusercontent.com/24240931/89743317-1d3dc080-da70-11ea-9d1a-745c5250732e.png">
<img width="497" alt="Screen Shot 2020-08-09 at 6 36 58 PM" src="https://user-images.githubusercontent.com/24240931/89743318-1d3dc080-da70-11ea-9013-abaf98132ecc.png">
<img width="501" alt="Screen Shot 2020-08-09 at 6 36 25 PM" src="https://user-images.githubusercontent.com/24240931/89743319-1dd65700-da70-11ea-94c5-302e197a74e9.png">
<img width="496" alt="Screen Shot 2020-08-09 at 6 36 08 PM" src="https://user-images.githubusercontent.com/24240931/89743320-1dd65700-da70-11ea-8a41-334504fc1e9f.png">
<img width="497" alt="Screen Shot 2020-08-09 at 6 35 50 PM" src="https://user-images.githubusercontent.com/24240931/89743321-1dd65700-da70-11ea-89f5-035010014205.png">
<img width="498" alt="Screen Shot 2020-08-09 at 6 35 16 PM" src="https://user-images.githubusercontent.com/24240931/89743323-1dd65700-da70-11ea-899d-04b662fc7783.png">
<img width="495" alt="Screen Shot 2020-08-09 at 6 34 32 PM" src="https://user-images.githubusercontent.com/24240931/89743324-1e6eed80-da70-11ea-86f8-239938f15649.png">
<img width="494" alt="Screen Shot 2020-08-09 at 6 34 08 PM" src="https://user-images.githubusercontent.com/24240931/89743325-1e6eed80-da70-11ea-8188-a1786f6f9f90.png">
<img width="492" alt="Screen Shot 2020-08-09 at 6 32 04 PM" src="https://user-images.githubusercontent.com/24240931/89743326-1e6eed80-da70-11ea-9a3c-d236b3b6f766.png">
<img width="496" alt="Screen Shot 2020-08-09 at 6 31 45 PM" src="https://user-images.githubusercontent.com/24240931/89743328-1e6eed80-da70-11ea-9f33-f56fe142251b.png">
<img width="501" alt="Screen Shot 2020-08-09 at 6 31 15 PM" src="https://user-images.githubusercontent.com/24240931/89743329-1e6eed80-da70-11ea-8a38-68fe41e3337c.png">
<img width="492" alt="Screen Shot 2020-08-09 at 6 30 50 PM" src="https://user-images.githubusercontent.com/24240931/89743330-1f078400-da70-11ea-8602-216f1348eedc.png">
<img width="496" alt="Screen Shot 2020-08-09 at 6 30 31 PM" src="https://user-images.githubusercontent.com/24240931/89743331-1f078400-da70-11ea-9da9-c4dc627a544d.png">
<img width="499" alt="Screen Shot 2020-08-09 at 6 30 05 PM" src="https://user-images.githubusercontent.com/24240931/89743332-1f078400-da70-11ea-850a-377ad98b129c.png">

**Comment by sanketghanmare** [comment]
These are my design choices for AutoViz. Let me know if you need any more changes

**Comment by AutoViML** [comment]
The last one looks good Sanket. If you want to edit the README.md page by adding the new logo and submit a pull request, you can. If not, I can go ahead and do it myself and give you credit for the logo. Let me know either way.

**Comment by AutoViML** [comment]
closed.
