### ISSUE TITLE
Categories barplot with target same color

### ISSUE THREAD

**Issue by Nathanlauga** [AutoViML/AutoViz#16]
Hi! 
I find out that for categories bar plot with target color splitting, **the color is the same for both target values**. I uploaded an example here : [test AutoViz on adult data notebook](https://github.com/Nathanlauga/test-autoviz/blob/master/Test%20autoviz%20on%20adult%20dataset.ipynb).

By the way, great job with this package !
Nathan.

**Comment by AutoViML** [comment]
Yes I see. Will fix that. Thanks for bribing this to my attention.
Ram

**Comment by AutoViML** [comment]
Nathan:
This color problem has been resolved. Please uninstall autoviz and install
a new version. Your version should say: 0.0.068

Otherwise you will see the old plots as you have in the notebook currently.
Thanks
Ran

**Comment by Nathanlauga** [comment]
Thanks! Good job :+1:
