### ISSUE TITLE
encoding issue  

### ISSUE THREAD

**Issue by hakobjan** [AutoViML/AutoViz#17]
I am trying to use AutoViz on a large data set with a shape of (1362132, 83)
THIS READS THE DATA SET

`df = pd.read_csv("./Desktop/mgh_multi_gifts_desc_joined_tb_CSV.csv",
                 error_bad_lines=False, 
                 engine='python',
                 sep=",",
                encoding='cp1252'`
 
THIS IS MY NEXT STEP

`encoding = "cp1252
error_bad_lines = False
engine ='python'
sep = ','
target = 'gift_amount'
datapath = './Desktop/'
filename = 'mgh_multi_gifts_desc_joined_tb_CSV.csv'
df = pd.read_csv(datapath+filename,sep=sep,index_col=None,
                 error_bad_lines = error_bad_lines,engine = engine,encoding=encoding)`

WHEN TRYING TO EXECUTE THIS NEXT STEP
`dft = AV.AutoViz(datapath+filename, sep=sep, depVar=target, dfte=None, header=0, verbose=0,
                            lowess=False,chart_format='svg',max_rows_analyzed=1500,max_cols_analyzed=30)`

GETTING THE FOLLOWING MASSAGE 

> File encoding decoder utf-8 does not work for this file
File encoding decoder iso-8859-11 does not work for this file
File encoding decoder cpl252 does not work for this file
File encoding decoder latin1 does not work for this file
None of the decoders work...
Not able to read or load file. Please check your inputs and try again...

NOT SURE WHAT TO DO NEXT , ANY HELP WOULD BE MUCH APPRECIATED.

**Comment by AutoViML** [comment]
Yes this is real easy to fix. If you have already loaded the data into a
data frame called “df” just send it to AutoViz directly as a DF as follows:

dft = AV.AutoViz(“”, sep=sep, depVar=target, dfte=df, header=0, verbose=0,
lowess=False,chart_format='svg',max_rows_analyzed=1500,max_cols_analyzed=30)

Try this. It should work.
Ram

**Comment by hakobjan** [comment]
> Yes this is real easy to fix. If you have already loaded the data into a data frame called “df” just send it to AutoViz directly as a DF as follows: dft = AV.AutoViz(“”, sep=sep, depVar=target, dfte=df, header=0, verbose=0, lowess=False,chart_format='svg',max_rows_analyzed=1500,max_cols_analyzed=30) Try this. It should work. Ram

Thanks for your response Ram!
what would the required filename argument be?

**Comment by AutoViML** [comment]
You just need to give the filename argument as an empty string “” as I have
shown below. You could have cut and pasted my code below in your notebook
and run it.
Ram
