### ISSUE TITLE
addition of example of how to install autoviz to workstation

### ISSUE THREAD

**Issue by 0xTimoo** [AutoViML/AutoViz#19]
this is to write an example of how to install autoviz to your user workstation

**Comment by AutoViML** [comment]
Hello Toby:
What do you mean by this comment? Is it a comment or a question?
Ram

**Comment by 0xTimoo** [comment]
Its a comment 

I mean in the documentation of the project, there should be an addition of how it can be  installed.

For example: (showing how it's been installed)

$cd <project_folder> where the project will be added to on the users PC

<project_folder>$ conda create -n <your_env_name> python=3.7 anaconda 
//the <your_env_name> will be the project_name
I hope this is clear, 

"Your_env_name" seems a little confusing to me when installing it, I think adding a comment that the "your_env_name" is the project folder name not a system_path will help clear it out.

**Comment by morenoh149** [comment]
@timoty-toby feel free to add such an example to the readme in a pr. Your instructions are still unclear to me.
