### ISSUE TITLE
DataFrame as input

### ISSUE THREAD

**Issue by Ashton-Sidhu** [AutoViML/AutoViz#22]
Hey just wondering if you're thinking about the ability to just pass a dataframe to AutoViz instead of the file.

I can help by creating a PR for it

**Comment by AutoViML** [comment]
It already takes in a dataframe an input. Check the documentation in README
where it says the fourth argument (input) is a dataframe “dfte” which
stands for dataframe. If you provide a dataframe to that argument it will
visualize that data frame.
Hope this helps.
