### ISSUE TITLE
Verbose = 2 does not save images

### ISSUE THREAD

**Issue by Metalkiler** [AutoViML/AutoViz#25]
Running verbose = 2 does not save the images anywhere!
Can you please see this issue?

**Comment by AutoViML** [comment]
It saves the images in the AutoViz_Class which has been initialized as AV.
You need to just use the dot notation to find the properties of AV to find
all the plots it has saved.
Ram

**Comment by Metalkiler** [comment]
But you could save each plot into a png or something with an option like verbose 
Instead I have to convert each xml to a png manually

**Comment by Metalkiler** [comment]
Also, it only works on Jupyter notebook if I want to run this code in a single script it gives an error (related to an in-line issue with ipython)

**Comment by AutoViML** [comment]
Let me change that and see if it works when I run it as a script. That’s a
good point you bring up. Thanks for letting me know
Ram

**Comment by Metalkiler** [comment]
And sorry again to bother you, but another question, if you run this package with a small dataset (e.g., iris) it does not give plots 
Is it normal?

**Comment by AutoViML** [comment]
That is not normal. In fact what you may find is that your data file is
missing or your target is missing or incorrectly spelled out. Please take a
screenshot and send it to me Via email at rsesha2001@yahoo.com

Thx
Ram

**Comment by Metalkiler** [comment]
Morning, I sent an email with that information

Also, how can you convert each stringIO plot you saved into several arrays into a single image 
Cause the solution I made was to gather the string (e.g., AV.barplots["plots"][0]) as presented in the image annexed and then saved into a pdf using pdfkit
 
However this is not an optimal solution (doing the way im doing) as presented in the pdf "out.pdf" . Is there a way to gather all plots into a Single xml file and save that pdf or png instead of saving into a class variable Only? That could be an Great addition to your package 😄 

PS: Check prints:

<img width="1102" alt="Captura de ecrã 2020-08-11, às 12 27 57" src="https://user-images.githubusercontent.com/39952471/89892346-6ad03f80-dbce-11ea-9b60-c90543b2e8c3.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/39952471/89892601-d0243080-dbce-11ea-9bbb-d1ca3a36b0ac.png">


<img width="1208" alt="image" src="https://user-images.githubusercontent.com/39952471/89892510-aa972700-dbce-11ea-81cc-569ac88f1864.png">

**Comment by AutoViML** [comment]
If you can modify the save_image_data module in AutoViz_Class to do what you wanted, then I can easily merge the changes into Autoviz.
For example, here is the code that saves image data in AutoViz_Class.py file:
``
######## This is where we store the image data in a dictionary with a list of images #########
def save_image_data(fig, image_count, chart_format):
    if chart_format == 'svg':
        ###### You have to add these lines to each function that creates charts currently ##
        imgdata = io.StringIO()
        fig.savefig(imgdata, format=chart_format)
        imgdata.seek(0)
        svg_data = imgdata.getvalue()
        return svg_data
    else:
        ### You have to do it slightly differently for PNG and JPEG formats
        imgdata = BytesIO()
        fig.savefig(imgdata, format=chart_format, bbox_inches='tight', pad_inches=0.0)
        imgdata.seek(0)
        figdata_png = base64.b64encode(imgdata.getvalue())
        return figdata_png

``
Can you try modifying it to do what you want?
Thanks
Ram

**Comment by AutoViML** [comment]
This issue has now been fixed with the latest version 0.0.72 which saves images to your local disk '/plots' folder if you use verbose=1 option for PNG and JPG images. However, SVG images are returned in AV_Class if you use verbose=2 option.

**Comment by Metalkiler** [comment]
Great addition!
Gonna test it soon!
