### ISSUE TITLE
AutoViz Crashes with the Error

### ISSUE THREAD

**Issue by gvyshnya** [AutoViML/AutoViz#26]
When I try to apply AutoViz to analizing the data of one of the competitions in Kaggle (namely, https://www.kaggle.com/c/lish-moa/data), it crashes. 

Below is the error trap I get

```
Imported AutoViz_Class version: 0.0.68. Call using: 
    from autoviz.AutoViz_Class import AutoViz_Class
    AV = AutoViz_Class()
    AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=0,
                            lowess=False,chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30)
            
To remove previous versions, perform 'pip uninstall autoviz'
Shape of your Data Set: (21948, 876)
Classifying variables in data set...
    875 Predictors classified...
        This does not include the Target column(s)
    2 variables removed since they were ID or low-information variables
    List of variables removed: ['sig_id', 'cp_type']
Since Number of Rows in data 21948 exceeds maximum, randomly sampling 2500 rows for EDA...
872 numeric variables in data exceeds limit, taking top 40 variables
Number of numeric variables = 872
    Number of variables removed due to high correlation = 227 
    Adding 1 categorical variables to reduced numeric variables  of 645
Selected No. of variables = 646 
Finding Important Features...
Not able to read or load file. Please check your inputs and try again...
```

My code to reproduce the problem is provided in https://gist.github.com/gvyshnya/7644fd77567051203ad96d95fbc7ef2a

I run that code on my local machine (not in a Kaggle kernel). The above-mentioned code expects the data files from the competition to be placed in *data* subfolder (relative to the folder where you place the python script with the code).

Below are the  key details about my OS and Python Environment

- Windows 10
- Python 3.7 in Anaconda
- AutoViz_Class version: 0.0.68

The trace from *pd.show_versions(as_json=False)* on my machine is provided below, just in case

```
INSTALLED VERSIONS
------------------
commit           : 2a7d3326dee660824a8433ffd01065f8ac37f7d6
python           : 3.7.0.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18362
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.1.2
numpy            : 1.19.2
pytz             : 2018.5
dateutil         : 2.7.3
pip              : 20.1
setuptools       : 49.2.0
Cython           : 0.28.5
pytest           : 5.3.2
hypothesis       : None
sphinx           : 1.7.9
blosc            : None
feather          : None
xlsxwriter       : 1.1.0
lxml.etree       : 4.2.5
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 6.5.0
pandas_datareader: None
bs4              : 4.6.3
bottleneck       : 1.2.1
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.1.2
numexpr          : 2.6.8
odfpy            : None
openpyxl         : 2.5.6
pandas_gbq       : 0.12.0
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.2.11
tables           : 3.4.4
tabulate         : 0.8.2
xarray           : None
xlrd             : 1.1.0
xlwt             : 1.3.0
numba            : 0.48.0
```

**Comment by AutoViML** [comment]
I have fixed a minor bug that was related to it. Please perform an upgrade of your AutoViz using the following command:

$ pip install autoviz --no-cache-dir --ignore-installed

Then you will see that a new version 0.0.70 has been installed. That should fix this problem. Please confirm to me so I can close this ticket.
Thx

**Comment by AutoViML** [comment]
George
I have fixed the problem. You should upgrade to the latest version by:
pip install autoviz —no-cache-dir —ignore-installed

That will get you version 0.0.70 which will fix it. Please note there is
still a limitation in mat plot library which makes drawing huge charts On
800 variables a challenge. So you may see an error after drawing most of
the charts. I still haven’t found a way around it. Yet.
Ram

**Comment by gvyshnya** [comment]
Thanks, Ram - appreciated your quick turn-around on it!

I tried it on my side locally, and version 0.0.70 worked (with the limitation on matplotlib side that you mentioned).

Thank you once again for your help and prompt fix.

George

**Comment by vik123446vbh** [comment]
I faced a similar issue where at the last code snippet I get  file not found /file not readable error

**Comment by AutoViML** [comment]
Vik:Can you please provide more color on what your problem is? This thread is so old that I don't remember what fixed it.ThxAuto Vimal
   On Tuesday, July 4, 2023 at 01:44:34 AM EDT, vik123446vbh ***@***.***> wrote:  
 
 


I faced a similar issue where at the last code snippet I get file not found /file not readable error

**Comment by vik123446vbh** [comment]
i'm sorry for that not so detailed question. I was working on this dataset
and I wanted to try out the autoviz package but I faced the error("Not able
to read or load file. Please check your inputs and try again...")
I have attached  two images below...
as you can see i can clearly import the file and then it says it can't
load/read it. Can you help me through this?

Thanks a lot
