### ISSUE TITLE
[Minor] AutoViz Crashes on the analysis of a dataset without any significant variables

### ISSUE THREAD

**Issue by gvyshnya** [AutoViML/AutoViz#27]
If AV is fed with a dataset where it does not find any significant variable to analize (vs. the target variable specified), it crashes.

The code to reproduce the issue is provided in https://gist.github.com/gvyshnya/c53321dbe947cc55fec91ccf6ae07294

The environment to reproduce the problem is the same as indicated in https://github.com/AutoViML/AutoViz/issues/26

The expected behaviour would be to gracefully finish the analysis session with a comprehensive inforamtion message to a user and without a crash.

**Comment by AutoViML** [comment]
George - I believe this has been fixed. Please confirm with the latest release on Github and let me know. Thanks,
