### ISSUE TITLE
How do we see output using a script file a terminal?

### ISSUE THREAD

**Issue by bansalism2** [AutoViML/AutoViz#28]
Hi AutoViML,

Firstly, congratulations and thanks for this wonderful package.
This works perfectly fine with Jupyter notebooks but how do I use the same if I am using an IDE let say Spyder?

Thanks in advance.
Mohit

**Comment by AutoViML** [comment]
Let me see what I can do. If we save the charts in PNG format in a sub
directory under the current directory, would that be a good solution?
Ram

**Comment by bansalism2** [comment]
Thanks Ram,

Or we could also do one thing, currently by default it runs in an "inline"
mode can we make that a parameter for the Class? whether user wants in "qt"
or "inline"?

**Comment by AutoViML** [comment]
Can u make the required modifications in code and submit a pull request if
it is possible...
Thx
Ram

**Comment by satishjasthi** [comment]
Hi Ram

Can I take up this issue

**Comment by AutoViML** [comment]
Satish:
Please do. Submit a pull request once you make the changes to the code.
I’ll review and approve or make further changes. Make sure you test on your
local drive first. Thanks
Ram

**Comment by AutoViML** [comment]
This feature has been added by Satish., Closing the issue.

**Comment by satishjasthi** [comment]
> This feature has been added by Satish., Closing the issue.

Hi Ram

Can you change the dir name in AutoViz_Class.py from 
`self.plots_dir = Path().cwd()/'plots'`
to 
`self.plots_dir = Path().cwd()/'Plots'`

because its failing to save the plots in 'Plots' dir while its actually creating 'plots' dir during AutoViz_Class initaliation

**Comment by AutoViML** [comment]
Yes I have changed it. You should see version 0.0.73 soon implementing it
on Github. I will upload it to a new version on PyPi later this week once I
have more changes. If you have any more suggestions to make let me know.
Ram

**Comment by satishjasthi** [comment]
Sure
