### ISSUE TITLE
AutoViz misidentifies my dependent variable as a categorical variable, which is in fact a continuous variable.

### ISSUE THREAD

**Issue by yoonwonj** [AutoViML/AutoViz#31]
AutoViz misidentifies my dependent variable as a categorical variable, which is in fact a continuous variable.

My dependent variable is the Loneliness scale score within the range of 1 of 4.
![image](https://user-images.githubusercontent.com/47551200/99041733-ca275c80-25ce-11eb-90cd-8a412a69083c.png)

When I run the basic code of Autoviz() below, I do not get any results regarding my dependent variable.
report_AV = AV.AutoViz('', dfte=data)

When I run the code containing depVar argument below, I get the results that appears to regard my dependent variable as a categorical variable. This makes the result useless for my research.
report_AV = AV.AutoViz('', dfte=data, depVar='Loneliness')

Here are some examples that I get from the above code.
![image](https://user-images.githubusercontent.com/47551200/99042104-83863200-25cf-11eb-8006-885a4aec42bc.png)

I've checked with the datatypes of my dataframe, and my dependent variable column's datatype is float64.

Is there any way to solve this issue?

**Comment by AutoViML** [comment]
Let me take a look and fix it. Should not be a problem.
Ram

**Comment by AutoViML** [comment]
Hello yoonwonj:

I have fixed the problem for you. You should install the fixed version from this github by opening a new Jupyter Notebook and typing this in an empty cell:

!pip install git+https://github.com/AutoViML/AutoViz.git

That will install the 0.0.75 version (pl check it) and it should be fixed. Please let me know if it works and I will close this issue.
Thx
Ram

**Comment by yoonwonj** [comment]
Hi, 

Sorry for getting back to you late. I've tried the fixed version and it worked perfectly well!

Thanks for your work.
