### ISSUE TITLE
maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by VellalaVineethKumar** [AutoViML/AutoViz#33]
I have a CSV file with 40,000 records and I was trying to run Autoviz on this data 
`from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
filename = 'Cleaned_InnerJoinedDataframe.csv'
df1 = AV.AutoViz(filename)`

But this fails with error
~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\font_manager.py in findfont(self, prop, fontext, directory, fallback_to_default, rebuild_if_missing)
   1236         return self._findfont_cached(
   1237             prop, fontext, directory, fallback_to_default, rebuild_if_missing,
-> 1238             rc_params)
   1239 
   1240     @lru_cache()

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by AutoViML** [comment]
People have tested AutoViz with half a million records and more than 100 variables and it has run fine.

If you can a small snippet of data, I can test and let you know. My email is listed on this Github.

Ram
