### ISSUE TITLE
The title part at the top of the output image is cut off

### ISSUE THREAD

**Issue by beobest2** [AutoViML/AutoViz#35]
When using `vervose=2` to output an `svg` or `png` file, there is an issue where the top title part is cut off.
There seems to be a problem with the `height` value setting, please check.

**Comment by beobest2** [comment]
![image](https://user-images.githubusercontent.com/7010554/104590312-7c9e9d00-56ae-11eb-9874-18022e56add4.png)

**Comment by AutoViML** [comment]
Sure let me take a look at it
Ram

**Comment by AutoViML** [comment]
Closed
