### ISSUE TITLE
Autoviz couldn't Process 100k records..Any solutions?

### ISSUE THREAD

**Issue by aswinjose89** [AutoViML/AutoViz#37]
Autoviz couldn't Process 100k records with 16 features..Any solutions?

**Comment by AutoViML** [comment]
Can you please review the following Kaggle Notebooks that have processed 300K records with similar number of features? They are Kaggle Data Sets. So you should be able to verify it. You might also want to try it on Colab or Kaggle kernels.

300K rows + 32 Variables on Kaggle:
https://www.kaggle.com/debarshichanda/autoviz-visualize-any-dataset-in-1-line/comments

Closing. Please let me know if this is still an issue.
Ram
