### ISSUE TITLE
Rows limit

### ISSUE THREAD

**Issue by atwahsz** [AutoViML/AutoViz#39]
Is there a way to overcome this ? I want autoviz to go through the whole data frame regardless of large number of rows

**Comment by rsesha** [comment]
yes you can set the max_rows_analyzed (see below) to a very large number in which case it will analyze all the rows in the data frame.

dft = AV.AutoViz(datapath+filename, sep=sep, depVar=target, dfte=df, header=0, verbose=2,
                            lowess=False,chart_format='svg',max_rows_analyzed=1500,max_cols_analyzed=30)

**Comment by ArijitSinghEDA** [comment]
@rsesha Is there any required minimum number of rows? Or is there any different minimum requirement? 
Sometimes it works with 100 rows of data, and sometimes it doesn't work with 200 rows of data.

**Comment by rsesha** [comment]
I don’t have any requirement on number of rows. You may have a problem with
the data format or something like that. Double check your input.
Ram

**Comment by AutoViML** [comment]
You can set the max_rows_analyzed (see below) to a very large number or None in which case it will analyze all the rows in the data frame.
    On Friday, February 9, 2024 at 10:12:35 PM EST, Ram Seshadri ***@***.***> wrote:  
 
 

I don’t have any requirement on number of rows. You may have a problem with
the data format or something like that. Double check your input.
Ram
