### ISSUE TITLE
DataFrame

### ISSUE THREAD

**Issue by ironapidevop** [AutoViML/AutoViz#40]
Dear all,
I couldn't figure out how to pass a dataframe (instead of a csv file) to `AV.AutoViz`.
Could somebody please give me a short hint?

thanks in advance.

**Comment by rsesha** [comment]
Can you check this and see if it works? 

dft = AV.AutoViz("", sep=sep, depVar=target, dfte=df, header=0, verbose=2,
                            lowess=False,chart_format='svg',max_rows_analyzed=1500,max_cols_analyzed=30)

If not, check this example demo:
https://github.com/AutoViML/AutoViz/blob/master/Examples/AutoViz_Demo.ipynb
