### ISSUE TITLE
AutoViz is recognizing int numbers as categorical vars, not numerical

### ISSUE THREAD

**Issue by aveusalex** [AutoViML/AutoViz#41]
When plotting charts, me and my team could see that numerical vars was being plotted as categorical vars. This means that an "age" data was being plotted as categories, like it was the same type as "card category" information.
    We have dealt with that only transforming the "age" information, that was int64 type, to float numbers, which seemed to have worked and treated correctly as numerical var.
    We used this dataset: https://www.kaggle.com/sakshigoyal7/credit-card-customers

**Comment by AutoViML** [comment]
Yes we treat integers as categories if the number of unique integer values in that column is less than 30.
If you want to treat it as a numeric variable, you can change it to float and it will treat it correctly.
