### ISSUE TITLE
Is it possible to have the input as dataframe instead of file?

### ISSUE THREAD

**Issue by hanzigs** [AutoViML/AutoViz#43]
if input is dataframe can be used in real time, files can be of any source and type

**Comment by AutoViML** [comment]
Autoviz accepts both files and dataframes as input. You just need to send one or the other in the calling function as below:
dfte : dataframe as input
filename = filename as input
sep = separator if using a file as input
-----------------------------------------------
dft = AV.AutoViz(
    filename,
    sep=",",
    depVar="",
    dfte=None,
    header=0,
    verbose=0,
    lowess=False,
    chart_format="svg",
    max_rows_analyzed=150000,
    max_cols_analyzed=30,
)
