### ISSUE TITLE
Normed Histogram plot with negative y value?

### ISSUE THREAD

**Issue by shuaiwang88** [AutoViML/AutoViz#45]
Hi, the plots I have all has negative y values. How to interpret this? 
<img width="519" alt="Screen Shot 2021-09-08 at 10 04 39 PM" src="https://user-images.githubusercontent.com/14266357/132610129-cde3e4db-6b4d-4421-abbc-6dcb821fb6b0.png">

I think the following code generates the plots. 
sns.distplot(dft.loc[dft[dep]==target_var][each_conti],bins=binsize, ax= ax1,
                            label=target_var, hist=False, kde=True,
                            color=color2)
                            legend_flag += 1

**Comment by AutoViML** [comment]
Hi @shuaiwang88 

Can you please clarify?? I am not understanding your issue. 
1. Are you suggesting AutoViz did something wrong and want to change its code to the one you have shown below?
`sns.distplot(dft.loc[dft[dep]==target_var][each_conti],bins=binsize, ax= ax1,
label=target_var, hist=False, kde=True,
color=color2)
legend_flag += 1`

2. Are you suggesting that AutoViz has a wrong plot but you don't know how to fix it and want me to change the code to fix it?

If it is #1, ok you can submit a pull request.

If it is #2, then I don't understand what is wrong with the plot. Can you please explain it?

Thx
R
