### ISSUE TITLE
Frequency distribution plot of target column is wrongly interpreted

### ISSUE THREAD

**Issue by Bhavana165** [AutoViML/AutoViz#47]
Hi, when I have run on the steel classification dataset the frequency distribution plot for the target column is showing wrong.
![Dist_Plots_target](https://user-images.githubusercontent.com/50872274/137694309-44b7d135-a834-4240-805d-11cfe27b6c31.png)

**Comment by Bhavana165** [comment]
And also the whole names of the columns are not showing in the graph.

**Comment by AutoViML** [comment]
Hi @Bhavana165 👍 
I have fixed this. Can you please upgrade via:

pip install autoviz --upgrade

thanks
AutoViz
