### ISSUE TITLE
Set output results path 

### ISSUE THREAD

**Issue by borisRa** [AutoViML/AutoViz#48]
Hi,

How can I control the  output file path ?

Thanks,
Boris

**Comment by AutoViML** [comment]
You can't. You need to use the folder that it saves the charts to. Why do you need to change the folder path?

**Comment by borisRa** [comment]
Because I would like to control where it saves the results.  for me the path should be different per each  problem ( different input data ). instead of copying it manually would like to control this from the code.

**Comment by sahanaraguram2000** [comment]
Yes I would like that too... I am using autoviz in a django app and I would like to store the results of each input data in a separate folder. Please help me out with this @AutoViML

**Comment by AutoViML** [comment]
Hi @borisRa 👍 
Sorry all for the trouble. I have fixed the bugs that was causing this verbose=2 error as well as  made an upgrade to save the plots in any directory you select. Please test it the upgraded version by:

pip install autoviz --upgrade

thanks for the feedback!

**Comment by borisRa** [comment]
> Hi @borisRa 👍 Sorry all for the trouble. I have fixed the bugs that was causing this verbose=2 error as well as made an upgrade to save the plots in any directory you select. Please test it the upgraded version by:
> 
> pip install autoviz --upgrade
> 
> thanks for the feedback!

Thank you very much !
