### ISSUE TITLE
Bokeh Option Unavailable

### ISSUE THREAD

**Issue by AustinCaudill** [AutoViML/AutoViz#49]
Per the documentation, when setting chart_format to "bokeh," an interactive dashboard should be created in the Jupyter Notebook.

However, I am receiving the following error:

`ValueError: Format 'bokeh' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)`

**Comment by AutoViML** [comment]
Hi Austin @AustinCaudill 
You must upgrade to the latest version of AutoViz by doing:
`!pip install autoviz --upgrade`

You should check out this example notebook for clues on how to set the chart format correctly:
[Example Notebook](https://github.com/AutoViML/AutoViz/blob/master/Examples/AutoViz_Bokeh_Interactive_Demo.ipynb)

**Comment by AustinCaudill** [comment]
That solved it, thank you.
