### ISSUE TITLE
Unable to Hide Plots

### ISSUE THREAD

**Issue by AustinCaudill** [AutoViML/AutoViz#51]
Setting verbose=2 does not hide the plots from being shown in either python script or python notebook.

**Comment by sahanaraguram2000** [comment]
Hello @AustinCaudill ! Are you able to run Autoviz in python script? 
DId you ever face this issue?
[Link to the issue](https://github.com/AutoViML/AutoViz/issues/50#issue-1044783023)
If yes, can you tell me how you overcame this?

**Comment by AutoViML** [comment]
Sorry all for the trouble. I have fixed the bugs that was causing this verbose=2 error as well as  made an upgrade to save the plots in any directory you select. Please test it the upgraded version by:

pip install autoviz --upgrade

thanks for the feedback!

**Comment by AustinCaudill** [comment]
Thank you for your quick work! I have tested and the issue is now resolved.
