### ISSUE TITLE
[suggestion] colab example notebooks

### ISSUE THREAD

**Issue by microprediction** [AutoViML/AutoViz#54]
Include some colab notebooks in the examples so lazy people (ahem) can just click and open them to see it work.

**Comment by nhatvietnam** [comment]
@microprediction  I do not think lazy people will fit in data science/AI, according to my experience they will not work long in this field.
Maybe just a couple of months they will start to look for other jobs!
By the way we still need AutoML tools for doing repetitive task automatically! Using auto tools does not mean you are lazy!
In addition, Autoviz is well documentation, I think it is better than my university power point slides in programming!

**Comment by microprediction** [comment]
you may be right but remember that laziness is one of the three virtues of a programmer.

**Comment by AutoViML** [comment]
I have added a Colab Demo notebook link to the main README page as well as there are Demo notebooks in the Examples page.

Here is a link if you want to look:
[Colab Notebook](https://colab.research.google.com/drive/1r5QqESRZDY98FFfDOgVtMAVA_oaGtqqx?usp=sharing)

**Comment by microprediction** [comment]
Thumbs up
