### ISSUE TITLE
HTMl and BOKEH not output all!

### ISSUE THREAD

**Issue by nhatvietnam** [AutoViML/AutoViz#55]
The autoviz work well for chart_format svg, but BOKEH and HTML not all the dataset work well, when running I encounter:

~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: ''

After searching through the internet, it seems like the problems is with the pandas!
Sorry but I do not know how to fix that!
Kind regard,

[autoviz_test.zip](https://github.com/AutoViML/AutoViz/files/7698983/autoviz_test.zip)

**Comment by AutoViML** [comment]
Hi @nhatvietnam 👍 
The issue was a minor code fix. I have fixed it now and should work. Here is the  same notebook with the fixed version running correctly. Please take a look.

[autoviz_test_fixed.zip](https://github.com/AutoViML/AutoViz/files/7699196/autoviz_test_fixed.zip)

you must do the following to upgrade on your local machine:

`pip install autoviz --upgrade`

You can close the issue if it is fixed.
AutoViML

**Comment by nhatvietnam** [comment]
Dear,

The issue is fixed but when I change the chart_format="server", the new error occurs as:

~\anaconda3\lib\site-packages\autoviz\AutoViz_Holo.py in draw_scatters_hv(dfin, nums, chart_format, problem_type, dep, classes, lowess, mk_dir, verbose)
    410     if chart_format in ['server', 'bokeh_server', 'bokeh-server']:
    411         #server = pn.serve(hv_all, start=True, show=True)
--> 412         hv_all.show()
    413     elif chart_format == 'html':
    414         save_html_data(hv_all, chart_format, plot_name, mk_dir)
[autoviz_test_server.zip](https://github.com/AutoViML/AutoViz/files/7699424/autoviz_test_server.zip)


AttributeError: 'str' object has no attribute 'show'


In addition, when using html output the scatterplot, it seems unnecessary because the packet output pair_scatters already!

**Comment by nhatvietnam** [comment]
This problem is done now!
