### ISSUE TITLE
chart_format="server" is not working!

### ISSUE THREAD

**Issue by nhatvietnam** [AutoViML/AutoViz#56]
Dear,
 I set the chart_format="server", the new error occurs as:

~\anaconda3\lib\site-packages\autoviz\AutoViz_Holo.py in draw_scatters_hv(dfin, nums, chart_format, problem_type, dep, classes, lowess, mk_dir, verbose)
    410     if chart_format in ['server', 'bokeh_server', 'bokeh-server']:
    411         #server = pn.serve(hv_all, start=True, show=True)
--> 412         hv_all.show()
    413     elif chart_format == 'html':
    414         save_html_data(hv_all, chart_format, plot_name, mk_dir)

AttributeError: 'str' object has no attribute 'show'

In addition, when using html output the scatterplot, it seems unnecessary because the packet output pair_scatters already! Furthermore, I am not sure it is packet error or my PC got problem but scatterplot in HTML output file is blank!
[autoviz_test_server.zip](https://github.com/AutoViML/AutoViz/files/7700213/autoviz_test_server.zip)

**Comment by AutoViML** [comment]
Hi @nhatvietnam 👍 
This has been fixed. Please upgrade AutoViz by:

pip install autoviz --upgrade

Please close this if it is fixed.
AutoViML

**Comment by nhatvietnam** [comment]
Dear!

It work now, you are awesome!

Kind regards,
