### ISSUE TITLE
lightgbm instead of xgboost

### ISSUE THREAD

**Issue by reza1615** [AutoViML/AutoViz#58]
Is t possible to use lightgbm instead of xgboost?
It is extremely faster and lighter

**Comment by rsesha** [comment]
Hi @reza1615 👍 

Great question.

I think that would require a small change but extensive testing to make sure nothing else is broken.

I will research this and let you know.
AutoViML

**Comment by AutoViML** [comment]
After researching LightGBM, there are no plans to switch to LightGBM since XGBoost is just as fast. Hence closing this request.
