### ISSUE TITLE
Could not draw ...

### ISSUE THREAD

**Issue by rgoubet** [AutoViML/AutoViz#59]
I'm trying to run autoviz on my pandas DataFrame and, oddly, sometimes it works, sometimes is does not and displays the following:

```
Shape of your Data Set loaded: (68, 7)
############## C L A S S I F Y I N G  V A R I A B L E S  ####################
Classifying variables in data set...
    6 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Multi_Classification VISUALIZATION Started #####################
Total Number of Scatter Plots = 10
Could not draw Distribution Plots
Could not draw Pivot Charts against Dependent Variable
Time to run AutoViz = 3 seconds 

 ###################### AUTO VISUALIZATION Completed ########################
```

As far as I can tell, nothing changes between the times when it works and when it does not. What can trigger this kind of error?

**Comment by rgoubet** [comment]
Seems like `%matplotlib inline` needs to run *after* the import. Since I usually place iPython magic commands at the top of my notebooks, it typically runs before the import, except in the case where I re-executed the cell.

**Comment by shalmali30** [comment]
Thank you so much! This worked for me too
