### ISSUE TITLE
No plot visible in local Jupiter  

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/AutoViz#61]
from autoviz.AutoViz_Class import AutoViz_Class
%matplotlib
AV = AutoViz_Class()
df = AV.AutoViz(filename='',dfte=train,depVar='Species',verbose=1)

Using matplotlib backend: Qt5Agg
Shape of your Data Set loaded: (150, 5)
############## C L A S S I F Y I N G  V A R I A B L E S  ####################
Classifying variables in data set...
    Number of Numeric Columns =  4
    Number of Integer-Categorical Columns =  0
    Number of String-Categorical Columns =  0
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    4 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Multi_Classification VISUALIZATION Started #####################
Data Set Shape: 150 rows, 5 cols
Data Set columns info:
* SepalLengthCm: 0 nulls, 35 unique vals, most common: {5.0: 10, 5.1: 9}
* SepalWidthCm: 0 nulls, 23 unique vals, most common: {3.0: 26, 2.8: 14}
* PetalLengthCm: 0 nulls, 43 unique vals, most common: {1.5: 14, 1.4: 12}
* PetalWidthCm: 0 nulls, 22 unique vals, most common: {0.2: 28, 1.3: 13}
* Species: 0 nulls, 3 unique vals, most common: {'Iris-setosa': 50, 'Iris-versicolor': 50}
--------------------------------------------------------------------
   Columns to delete:
'   []'
   Boolean variables %s 
'   []'
   Categorical variables %s 
'   []'
   Continuous variables %s 
"   ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']"
   Discrete string variables %s 
'   []'
   Date and time variables %s 
'   []'
   ID variables %s 
'   []'
   Target variable %s 
'   Species'
Total Number of Scatter Plots = 10
No categorical or boolean vars in data set. Hence no pivot plots...
No categorical or numeric vars in data set. Hence no bar charts.
Time to run AutoViz = 2 seconds 

 ###################### AUTO VISUALIZATION Completed ########################

but no plot.

In kaggle it' was working fine

https://www.kaggle.com/gauravduttakiit/multi-classification-problem-iris/notebook

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 👍 
You didn't get the sequence of commands above right. You must do %matplotlib inline after you create the AutoViz_Class.
```
import pandas as pd
import numpy as np
###########  import Autoviz_Class ##################
from autoviz.AutoViz_Class import AutoViz_Class
###########  set up the data ##################
datapath = '../Ram/Data_Sets/'
file_name = 'iris.csv'
depVar = 'typeclass'
sep=','
###########  Create the autoviz_class ###############
AV = AutoViz_Class()
###########  do %matplotlib inline now ############
%matplotlib inline
###########  Now run Autoviz ##################
_ = AV.AutoViz(datapath+file_name)
```
This sequence above works fine and displays the charts in my Jupyter Notebook (laptop).
AutoViML

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 🥇 
If you need to download a notebook that works and you can test you data on it: here it is

https://github.com/AutoViML/AutoViz/blob/master/Examples/AutoViz_Demo.ipynb

AutoViML
