### ISSUE TITLE
incorrect categorical variable assignment

### ISSUE THREAD

**Issue by zeydabadi** [AutoViML/AutoViz#64]
I have a dataframe that has 32 columns of type object and float.32
one of the float.32 columns is treated as categorical by AutoViz.
How can I exclude that column from being treated as categorical?

**Comment by AutoViML** [comment]
Hi @zeydabadi:
AutoViz checks if the number of unique values in your float.32 is below the `float_limit = 15` - in your case, it appears that it seems to fit this criteria. hence it is treating that float.32 column as a categorical variable. Is there anything you would like me to change here?
Thanks
AutoViML
