### ISSUE TITLE
Read CSV file with different encodings

### ISSUE THREAD

**Issue by gaspar-avit** [AutoViML/AutoViz#65]
Hi. I'm trying to use the library with a CSV file that uses "ISO-8859-1" encoding, and the log says:

`pandas ascii encoder does not work for this file. Continuing...`
` pandas utf-8 encoder does not work for this file. Continuing...`
` pandas iso-8859-1 encoder does not work for this file. Continuing...`

After checking the source code, I found that there is a bug in the AutoViz_Utils.py file:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/84574031/160566021-39a96083-76fb-442e-ae6d-0e77781547a9.png">

Here there is a for loop to try with different encodings but, as it can be seen, the `encoding` parameter of the `pd.read_csv` function is always set to `None`.

Please, check this, maybe I'm missing something.
Thanks in advance.

**Comment by AutoViML** [comment]
Hi @gaspar-avit 👍 
You are right. Fixing it right now. You should try it with:
```
pip install autoviz --upgrade
```

Check for version number 0.1.37

Thanks
AutoViML
