### ISSUE TITLE
ModuleNotFoundError: No module named 'autoviz.AutoViz_class'

### ISSUE THREAD

**Issue by kittu1999** [AutoViML/AutoViz#67]
----> from autoviz.AutoViz_class import AutoViz_class

ModuleNotFoundError: No module named 'autoviz.AutoViz_class'

**Comment by AutoViML** [comment]
Hi @kittu1999 👍 
Very simple :-) - You could have checked the web site main README: https://github.com/AutoViML/AutoViz
it shows how to import.
```
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
```
You had a spelling mistake in your import (Upper case).
AutoViML
