### ISSUE TITLE
IndexError: list index out of range if type(df[depVar])==int32

### ISSUE THREAD

**Issue by ZhaiCong** [AutoViML/AutoViz#69]
if the type of target columns is int32，it seems meet some mistake ,because the function classify_print_vars does not treat type(int32). if I define  target columns astype int64, the problem will solve.
please add the infer function to type int32. Thanks！

![image](https://user-images.githubusercontent.com/26532631/165308167-155058c2-51df-438c-9510-9f6081f378da.png)

    if type(depVar) == str:
        if depVar == '':
            cols_list = list(dft)
            problem_type = 'Clustering'
            classes = []
        else:
            try:
                problem_type = analyze_problem_type(dft, depVar,verbose)
            except:
                print('Could not find given target var in data set. Please check input')
                ### return the data frame as is ############
                return dfte
            cols_list = list_difference(list(dft),depVar)
            if dft[depVar].dtype == object:
                classes = dft[depVar].factorize()[1].tolist()
                #### You dont have to convert it since most charts can take string vars as target ####
                #dft[depVar] = dft[depVar].factorize()[0]
            elif dft[depVar].dtype == np.int64:          ###################here#################             
                classes = dft[depVar].factorize()[1].tolist()
            elif dft[depVar].dtype == bool:
                dft[depVar] = dft[depVar].astype(int)
                classes =  dft[depVar].unique().astype(int).tolist()
            elif dft[depVar].dtype == float and problem_type.endswith('Classification'):
                classes = dft[depVar].factorize()[1].tolist()
            else:
                classes = []

**Comment by AutoViML** [comment]
Hi @ZhaiCong 👍 
Nice Catch! I fixed the bug and you can test it by upgrading via:
```
pip install autoviz --upgrade
```
Thanks for trying out AutoViz.
AutoViML
