### ISSUE TITLE
"Not able to read or load file. Please check your inputs and try again..."

### ISSUE THREAD

**Issue by isioma42** [AutoViML/AutoViz#7]
hello Ram,
when i run the code on my dateset, dft = av.AutoViz('', sep, target, df)
i get this error
"Not able to read or load file. Please check your inputs and try again..."

what could the issue be?

**Comment by isioma42** [comment]
![Screen Shot 2019-11-20 at 4 38 39 PM](https://user-images.githubusercontent.com/41458615/69285317-99306980-0bbe-11ea-99f9-f2d2ec73cb9c.png)

**Comment by isioma42** [comment]
sep = ''
target = 'Instance ID'

dft = av.AutoViz('', sep, target, df)

**Comment by AutoViML** [comment]
Can you please load your notebook and a small slice of your data set to
some GitHub and point me to it? Or you can attach a small CSV data set to
your Bug / Issue if that’s possible. Only then can I try to reproduce the
problem.
Thx
Ram

**Comment by isioma42** [comment]
Hi Ram,

Here is the link to dataset
https://github.com/isioma42/machine-learning/blob/master/sample%20ec2%20metrics.xlsx


and the notebook

https://github.com/isioma42/machine-learning/blob/master/new.ipynb

best
Isi

**Comment by AutoViML** [comment]
It seems to run fine with your data set if you chose a different target
variable than "Instance ID".
Typically ID variables don't have any useful info so they get deleted by
AutoViz. In this case, thats what happened. Take a look at my Jupyter
Notebook attached. It seems to work fine when you choose a different target
variable such as "Sum" or "Average".
Ram

**Comment by isioma42** [comment]
Thank you , I donot see the file attached.

**Comment by AutoViML** [comment]
Can you post an email to the Address on my Auto_ViML page?
Ram

**Comment by isioma42** [comment]
isiomamasi@gmail.com

**Comment by AutoViML** [comment]
This issue is now closed. Please reopen it if you need any further help.
