### ISSUE TITLE
Loading file Failure

### ISSUE THREAD

**Issue by danielhassin** [AutoViML/AutoViz#70]
I am running another pd.DataFrame and get the error "Not able to read or load file. Please check your inputs and try again...". how can I detect the problem in my input?
**Edit** - succeeded to run and plot the mentioned df, but when defining "DepVar" I still get the notification "Not able to read or load file. Please check your inputs and try again...".
**Edit 2** - succeeded to run and plot the mentioned df with defined "DepVar", but it happened after I changed the "max_cols_analyzed" from 20 to 30. makes sense? 

thanks!

**Comment by AutoViML** [comment]
@danielhassin 👍 
This was a minor bug which has been fixed. Please upgrade your installation (see below) and try again:
```
pip install autoviz --upgrade --ignore-installed
```
Thanks
AutoViML team
