### ISSUE TITLE
No plots showing up in output of code block

### ISSUE THREAD

**Issue by reachshyamal** [AutoViML/AutoViz#72]
Please find the screenshot of the output of invoking AutoViz class on a dataset in Google Colab notebook.

![image](https://user-images.githubusercontent.com/42542338/178426257-39138f76-5a6d-402f-8987-e35a88c5dbbf.png)

**Comment by reachshyamal** [comment]
I am running this as well in the code block above
!pip install autoviz --no-cache-dir --ignore-installed

The output is the following:
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting autoviz
  Downloading autoviz-0.1.41-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 5.2 MB/s 
Collecting typing-extensions>=4.1.1
  Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting emoji
  Downloading emoji-1.7.0.tar.gz (175 kB)
     |████████████████████████████████| 175 kB 11.1 MB/s 
Collecting statsmodels
  Downloading statsmodels-0.13.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 45.3 MB/s 
Collecting panel~=0.12.6
  Downloading panel-0.12.7-py2.py3-none-any.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 44.1 MB/s 
Collecting numpy
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 53.5 MB/s 
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 52.4 MB/s 
Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 55.6 MB/s 
Collecting matplotlib>=3.3.3
  Downloading matplotlib-3.5.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 47.7 MB/s 
Collecting fsspec>=0.8.3
  Downloading fsspec-2022.5.0-py3-none-any.whl (140 kB)
     |████████████████████████████████| 140 kB 85.5 MB/s 
Collecting xgboost>=0.82
  Downloading xgboost-1.6.1-py3-none-manylinux2014_x86_64.whl (192.9 MB)
     |████████████████████████████████| 192.9 MB 1.1 MB/s 
Collecting pyamg
  Downloading pyamg-4.2.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 33.2 MB/s 
Collecting hvplot>=0.7.3
  Downloading hvplot-0.8.0-py2.py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 46.3 MB/s 
Collecting nltk
  Downloading nltk-3.7-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 64.6 MB/s 
Collecting holoviews>=1.14.6
  Downloading holoviews-1.15.0-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 43.0 MB/s 
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     |████████████████████████████████| 24.8 MB 1.1 MB/s 
Collecting bokeh>=2.4.2
  Downloading bokeh-2.4.3-py3-none-any.whl (18.5 MB)
     |████████████████████████████████| 18.5 MB 43.8 MB/s 
Collecting wordcloud
  Downloading wordcloud-1.8.2.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
     |████████████████████████████████| 435 kB 75.4 MB/s 
Collecting ipython
  Downloading ipython-7.34.0-py3-none-any.whl (793 kB)
     |████████████████████████████████| 793 kB 60.1 MB/s 
Collecting seaborn>=0.11.1
  Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
     |████████████████████████████████| 292 kB 59.9 MB/s 
Collecting pandas
  Downloading pandas-1.3.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 43.2 MB/s 
Collecting pillow>=7.1.0
  Downloading Pillow-9.2.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 53.6 MB/s 
Collecting tornado>=5.1
  Downloading tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
     |████████████████████████████████| 423 kB 46.2 MB/s 
Collecting Jinja2>=2.9
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 83.8 MB/s 
Collecting PyYAML>=3.10
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 71.3 MB/s 
Collecting packaging>=16.8
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 40.9 MB/s 
Collecting param<2.0,>=1.9.3
  Downloading param-1.12.2-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 47.5 MB/s 
Collecting holoviews>=1.14.6
  Downloading holoviews-1.14.9-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 41.4 MB/s 
Collecting colorcet
  Downloading colorcet-3.0.0-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 53.2 MB/s 
Collecting pyviz-comms>=0.7.4
  Downloading pyviz_comms-2.2.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 27.0 MB/s 
Collecting pyct>=0.4.4
  Downloading pyct-0.4.8-py2.py3-none-any.whl (15 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 56.6 MB/s 
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 42.9 MB/s 
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 52.0 MB/s 
Collecting fonttools>=4.22.0
  Downloading fonttools-4.34.4-py3-none-any.whl (944 kB)
     |████████████████████████████████| 944 kB 60.5 MB/s 
Collecting pytz>=2017.3
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 59.6 MB/s 
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 34.1 MB/s 
Collecting bleach
  Downloading bleach-5.0.1-py3-none-any.whl (160 kB)
     |████████████████████████████████| 160 kB 59.5 MB/s 
Collecting tqdm>=4.48.0
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 57.0 MB/s 
Collecting setuptools<61,>=42
  Downloading setuptools-60.10.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 51.6 MB/s 
Collecting markdown
  Downloading Markdown-3.3.7-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 49.4 MB/s 
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting scipy>=1.0
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 1.2 MB/s 
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting jedi>=0.16
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 60.6 MB/s 
Collecting pexpect>4.3
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 51.4 MB/s 
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting matplotlib-inline
  Downloading matplotlib_inline-0.1.3-py3-none-any.whl (8.2 kB)
Collecting traitlets>=4.2
  Downloading traitlets-5.3.0-py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 46.1 MB/s 
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.30-py3-none-any.whl (381 kB)
     |████████████████████████████████| 381 kB 54.3 MB/s 
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pygments
  Downloading Pygments-2.12.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 49.8 MB/s 
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 39.2 MB/s 
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting ipykernel
  Downloading ipykernel-6.15.1-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 54.3 MB/s 
Collecting notebook
  Downloading notebook-6.4.12-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 35.3 MB/s 
Collecting nbconvert
  Downloading nbconvert-6.5.0-py3-none-any.whl (561 kB)
     |████████████████████████████████| 561 kB 72.9 MB/s 
Collecting ipywidgets
  Downloading ipywidgets-7.7.1-py2.py3-none-any.whl (123 kB)
     |████████████████████████████████| 123 kB 62.2 MB/s 
Collecting jupyter-console
  Downloading jupyter_console-6.4.4-py3-none-any.whl (22 kB)
Collecting qtconsole
  Downloading qtconsole-5.3.1-py3-none-any.whl (120 kB)
     |████████████████████████████████| 120 kB 57.6 MB/s 
Collecting pyzmq>=17
  Downloading pyzmq-23.2.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 57.0 MB/s 
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-7.3.4-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 87.7 MB/s 
Collecting debugpy>=1.0
  Downloading debugpy-1.6.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 30.1 MB/s 
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Collecting psutil
  Downloading psutil-5.9.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
     |████████████████████████████████| 281 kB 64.7 MB/s 
Collecting entrypoints
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Collecting jupyter-core>=4.9.2
  Downloading jupyter_core-4.11.1-py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 50.5 MB/s 
Collecting ipython-genutils~=0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jupyterlab-widgets>=1.0.0
  Downloading jupyterlab_widgets-1.1.1-py3-none-any.whl (245 kB)
     |████████████████████████████████| 245 kB 53.7 MB/s 
Collecting widgetsnbextension~=3.6.0
  Downloading widgetsnbextension-3.6.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 47.6 MB/s 
Collecting argon2-cffi
  Downloading argon2_cffi-21.3.0-py3-none-any.whl (14 kB)
Collecting prometheus-client
  Downloading prometheus_client-0.14.1-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 50.9 MB/s 
Collecting Send2Trash>=1.8.0
  Downloading Send2Trash-1.8.0-py3-none-any.whl (18 kB)
Collecting terminado>=0.8.3
  Downloading terminado-0.15.0-py3-none-any.whl (16 kB)
Collecting nbformat
  Downloading nbformat-5.4.0-py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 38.3 MB/s 
Collecting tinycss2
  Downloading tinycss2-1.1.1-py3-none-any.whl (21 kB)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting nbclient>=0.5.0
  Downloading nbclient-0.6.6-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 8.8 MB/s 
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 48.0 MB/s 
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.2.2-py2.py3-none-any.whl (21 kB)
Collecting fastjsonschema
  Downloading fastjsonschema-2.15.3-py3-none-any.whl (22 kB)
Collecting jsonschema>=2.6
  Downloading jsonschema-4.7.2-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 45.6 MB/s 
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
     |████████████████████████████████| 117 kB 47.5 MB/s 
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-5.8.0-py3-none-any.whl (28 kB)
Collecting attrs>=17.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 48.1 MB/s 
Collecting importlib-metadata
  Downloading importlib_metadata-4.12.0-py3-none-any.whl (21 kB)
Collecting zipp>=3.1.0
  Downloading zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting argon2-cffi-bindings
  Downloading argon2_cffi_bindings-21.2.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (86 kB)
     |████████████████████████████████| 86 kB 44.1 MB/s 
Collecting cffi>=1.0.1
  Downloading cffi-1.15.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
     |████████████████████████████████| 427 kB 38.5 MB/s 
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 47.1 MB/s 
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting regex>=2021.8.3
  Downloading regex-2022.7.9-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (749 kB)
     |████████████████████████████████| 749 kB 62.7 MB/s 
Collecting joblib
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     |████████████████████████████████| 306 kB 70.7 MB/s 
Collecting click
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 65.8 MB/s 
Collecting qtpy>=2.0.1
  Downloading QtPy-2.1.0-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 49.1 MB/s 
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 64.1 MB/s 
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.10-py2.py3-none-any.whl (139 kB)
     |████████████████████████████████| 139 kB 55.7 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     |████████████████████████████████| 160 kB 64.2 MB/s 
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting patsy>=0.5.2
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 53.7 MB/s 
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171046 sha256=aa3c3516193545e32c006d68af90a76dea1c2cc286a90a34be6707f3dc111bf8
  Stored in directory: /tmp/pip-ephem-wheel-cache-ic5nuik2/wheels/8a/4e/b6/57b01db010d17ef6ea9b40300af725ef3e210cb1acfb7ac8b6
Successfully built emoji
Installing collected packages: zipp, typing-extensions, traitlets, six, pyrsistent, importlib-resources, importlib-metadata, attrs, wcwidth, tornado, pyzmq, python-dateutil, pycparser, ptyprocess, parso, nest-asyncio, jupyter-core, jsonschema, fastjsonschema, entrypoints, webencodings, soupsieve, setuptools, pyparsing, pygments, prompt-toolkit, pickleshare, pexpect, nbformat, matplotlib-inline, MarkupSafe, jupyter-client, jedi, decorator, cffi, backcall, tinycss2, psutil, pandocfilters, packaging, nbclient, mistune, jupyterlab-pygments, Jinja2, ipython, defusedxml, debugpy, bleach, beautifulsoup4, argon2-cffi-bindings, urllib3, terminado, Send2Trash, PyYAML, prometheus-client, pillow, param, numpy, nbconvert, ipython-genutils, ipykernel, idna, charset-normalizer, certifi, argon2-cffi, tqdm, requests, pyviz-comms, pytz, pyct, notebook, markdown, bokeh, widgetsnbextension, regex, qtpy, panel, pandas, kiwisolver, jupyterlab-widgets, joblib, fonttools, cycler, colorcet, click, threadpoolctl, scipy, qtconsole, patsy, nltk, matplotlib, jupyter-console, ipywidgets, holoviews, xlrd, xgboost, wordcloud, textblob, statsmodels, seaborn, scikit-learn, pyamg, jupyter, hvplot, fsspec, emoji, autoviz
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.0.17 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.3.0 which is incompatible.
spacy 3.3.1 requires typing-extensions<4.2.0,>=3.7.4; python_version < "3.8", but you have typing-extensions 4.3.0 which is incompatible.
moviepy 0.2.3.5 requires decorator<5.0,>=4.0.2, but you have decorator 5.1.1 which is incompatible.
google-colab 1.0.0 requires ipykernel~=4.10, but you have ipykernel 6.15.1 which is incompatible.
google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.34.0 which is incompatible.
google-colab 1.0.0 requires notebook~=5.3.0; python_version >= "3.0", but you have notebook 6.4.12 which is incompatible.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.1 which is incompatible.
google-colab 1.0.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.
google-colab 1.0.0 requires tornado~=5.1.0; python_version >= "3.0", but you have tornado 6.2 which is incompatible.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.1 PyYAML-6.0 Send2Trash-1.8.0 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 attrs-21.4.0 autoviz-0.1.41 backcall-0.2.0 beautifulsoup4-4.11.1 bleach-5.0.1 bokeh-2.4.3 certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.0 click-8.1.3 colorcet-3.0.0 cycler-0.11.0 debugpy-1.6.2 decorator-5.1.1 defusedxml-0.7.1 emoji-1.7.0 entrypoints-0.4 fastjsonschema-2.15.3 fonttools-4.34.4 fsspec-2022.5.0 holoviews-1.14.9 hvplot-0.8.0 idna-3.3 importlib-metadata-4.12.0 importlib-resources-5.8.0 ipykernel-6.15.1 ipython-7.34.0 ipython-genutils-0.2.0 ipywidgets-7.7.1 jedi-0.18.1 joblib-1.1.0 jsonschema-4.7.2 jupyter-1.0.0 jupyter-client-7.3.4 jupyter-console-6.4.4 jupyter-core-4.11.1 jupyterlab-pygments-0.2.2 jupyterlab-widgets-1.1.1 kiwisolver-1.4.3 markdown-3.3.7 matplotlib-3.5.2 matplotlib-inline-0.1.3 mistune-0.8.4 nbclient-0.6.6 nbconvert-6.5.0 nbformat-5.4.0 nest-asyncio-1.5.5 nltk-3.7 notebook-6.4.12 numpy-1.21.6 packaging-21.3 pandas-1.3.5 pandocfilters-1.5.0 panel-0.12.7 param-1.12.2 parso-0.8.3 patsy-0.5.2 pexpect-4.8.0 pickleshare-0.7.5 pillow-9.2.0 prometheus-client-0.14.1 prompt-toolkit-3.0.30 psutil-5.9.1 ptyprocess-0.7.0 pyamg-4.2.3 pycparser-2.21 pyct-0.4.8 pygments-2.12.0 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 pytz-2022.1 pyviz-comms-2.2.0 pyzmq-23.2.0 qtconsole-5.3.1 qtpy-2.1.0 regex-2022.7.9 requests-2.28.1 scikit-learn-1.0.2 scipy-1.7.3 seaborn-0.11.2 setuptools-60.10.0 six-1.16.0 soupsieve-2.3.2.post1 statsmodels-0.13.2 terminado-0.15.0 textblob-0.17.1 threadpoolctl-3.1.0 tinycss2-1.1.1 tornado-6.2 tqdm-4.64.0 traitlets-5.3.0 typing-extensions-4.3.0 urllib3-1.26.10 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.6.1 wordcloud-1.8.2.2 xgboost-1.6.1 xlrd-2.0.1 zipp-3.8.0

WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Disconnect and delete runtime" from the "Runtime" menu.
WARNING: The following packages were previously imported in this runtime:
  [IPython,PIL,_distutils_hack,attr,autoviz,bleach,bokeh,bs4,certifi,cffi,charset_normalizer,colorcet,cycler,dateutil,debugpy,decorator,defusedxml,emoji,fastjsonschema,holoviews,hvplot,idna,importlib_metadata,importlib_resources,ipython_genutils,ipywidgets,jedi,jinja2,joblib,jupyterlab_pygments,kiwisolver,markupsafe,matplotlib,matplotlib_inline,mistune,mpl_toolkits,nbclient,nbconvert,nbformat,nltk,notebook,numpy,packaging,pandas,pandocfilters,panel,param,parso,pexpect,pickleshare,pkg_resources,prompt_toolkit,psutil,pvectorc,pygments,pyrsistent,pytz,pyviz_comms,regex,requests,scipy,seaborn,setuptools,six,sklearn,statsmodels,textblob,tornado,tqdm,urllib3,wcwidth,webencodings,wordcloud,xgboost,xlrd,yaml,zipp,zmq]
You must restart the runtime in order to use newly installed versions.

**Comment by AutoViML** [comment]
You need to execute 
```
%matplotlib inline
```
In the notebook before running AutoViz. Otherwise no plots will be displayed.

**Comment by reachshyamal** [comment]
I am already executing that, but still no plots are showing up

**Comment by AutoViML** [comment]
The sequence is as follows
from autoviz.AutoViz_Class import AutoViz_Class
then initialize AV
AV = AutoViz_Class()

Then perform %matplotlib
%matplotlib inline 

Then call AV.AutoViz(filename)
See image here:
![image](https://user-images.githubusercontent.com/51647480/178738838-f153a622-d0c9-4974-917f-d0a19809ea13.png)

**Comment by reachshyamal** [comment]
Thanks , I didn't know that I needed to import seaborn , but appreciate the code snippet! It worked!

**Comment by Ali-Flt** [comment]
I use autoviz in my project and by only importing autoviz in a part of my code, no plots created from other parts of my codes are shown on spyder anymore unless I run `%matplotlib inline`. Why should importing a package break the functionality of the whole program?
