### ISSUE TITLE
Can not draw Wordcloud plot 

### ISSUE THREAD

**Issue by tonovoh1** [AutoViML/AutoViz#74]
Shape of your Data Set loaded: (3312, 20)
#######################################################################################
#######################################################################################
Classifying variables in data set...
    20 Predictors classified...
        2 variables removed since they were ID or low-information variables
Number of All Scatter Plots = 6
Could not draw wordcloud plot for Order ID
Could not draw wordcloud plot for Product ID
Could not draw wordcloud plot for Product Name
Could not draw wordcloud plot for Customer ID
Could not draw wordcloud plot for Customer Name
Could not draw wordcloud plot for City
Time to run AutoViz = 5 seconds 

 ###################### AUTO VISUALIZATION Completed ########################

**Comment by tonovoh1** [comment]
AV = AutoViz_Class()
df_autoviz = AV.AutoViz('data.xlsx')

that is the code i ran and that is the output it shows

**Comment by AutoViML** [comment]
Hi @tonovoh1 👍 
Can you please check if u have the latest version of AutoViz since this problem with wordclouds has been fixed in the latest version.  Can you try your code once again after upgrading via:

```
pip install autoviz --upgrade
```

**Comment by AutoViML** [comment]
Hi @tonovoh1 👍 

I found there was a bug that prevented Wordcloud plots. So please go ahead and upgrade:

```
pip install autoviz --upgrade
```

If you see version 0.1.43 then you have got the right version.
