### ISSUE TITLE
[Suggestion] output save as object in memory.

### ISSUE THREAD

**Issue by LiebeLee** [AutoViML/AutoViz#75]
Thanks for creating this amazing tool!

In some cases, like the back end and front end are separated, the generaed files may need to be stored into the memory and then return to the front end.
Will this feature can be considered to add  to the future version?

Thank you.

**Comment by AutoViML** [comment]
Hi @LiebeLee 👍 
Thanks for your comments on AutoViz. This is a good suggestion but writing large image files to disk and then retrieving them may slow AutoViz down. Have you tried the `verbose=2` option which saves all image files to disk? You can then load them yourself and visualize them.
