### ISSUE TITLE
"panel" dependency support for the latest version

### ISSUE THREAD

**Issue by celestinoxp** [AutoViML/AutoViz#77]
requirements.txt have an dependecie "panel" in 12.x version. is too old.
new version of panel is 0.14.x and have a new bugfixes. 

Suggestion:
panel~=0.12.6 ---> support new panel version (0.14.0)

**Comment by AutoViML** [comment]
Hi @celestinoxp thanks for the suggestion. 👍 
I haven't tested it with panel 0.14.0 = so the best I can do is to change the `panel~=0.12.6` ---> `panel>=0.12.6`

Hope you can test it with 0.14.0 and tell me if everything works well with AutoViz with a couple of data sets.

I will then change `requirements.txt` to the latest version.
Thanks
AutoVimal

**Comment by celestinoxp** [comment]
1
After updating to the latest changes, autoviz continues to install "panel" 0.12.6.
After checking the setup.py file, I found that the dependencies remain with "panel" 0.12.6.

I don't have much experience in github and I was wondering if the requirements.txt dependency file is not being used and just setup.py. I think normally setup.py does the calling of dependencies from requirements.txt, which is not the case.

So I think you should change the version of the panel in setup.py

2
You can check usage of requirements.txt in setup.py, and you can use optional requirements, example here:
setup.py - https://github.com/pycaret/pycaret/blob/master/setup.py
requirements.txt - https://github.com/pycaret/pycaret/blob/master/requirements.txt
requirements-optional.txt - https://github.com/pycaret/pycaret/blob/master/requirements-optional.txt

**Comment by AutoViML** [comment]
I have changed the `setup.py` file as well. Good luck!
