### ISSUE TITLE
Failed DataFrames as input to the AutoViz

### ISSUE THREAD

**Issue by albertoecf** [AutoViML/AutoViz#79]
Hey :D hope you're doing great. Thanks and congrats for all of your achievements 
### Feature: 
Improved handling of pandas DataFrames as input to the AutoViz() function
### Expected change in behavior: 
The AutoViz() function should be able to handle pandas DataFrames as input, regardless of the data types of the columns or the presence of missing values.
### How to test it: 
Test the feature by passing a pandas DataFrame as input to the AutoViz() function and check that the visualizations are generated correctly.

Please note that the current version of autoviz library has a limitation when handling dataframes with missing values and columns with different data types.

Example code : 
```
from autoviz.AutoViz_Class import AutoViz_Class

# Initialize the AutoViz class
AV = AutoViz_Class()

# Run the 'AutoViz' function
AV.AutoViz(df)
```

With df a pandas DataFrame with numeric non value column 

![Captura de pantalla 2023-01-17 a las 12 14 53](https://user-images.githubusercontent.com/81099969/212885101-d9b174b7-2bf7-48a3-a5b6-1743c4f99ffc.png)

**Comment by AutoViML** [comment]
@albertoecf 
thanks for trying out AutoViz 👍 

You cannot run AV.AutoViz() directly by sending in a dataframe. It assumes that the default for AV.AutoViz () is a filename.

Hence you need to send in the input like this:

```
# Run the 'AutoViz' function
AV.AutoViz(filename="". dfte=df)
```

Then it will work. That's how the syntax was designed, I may try to change it one day like the way you are using it. But no time.

Thanks
Auto Vimal

**Comment by albertoecf** [comment]
Thanksss!!  Properly working with the provided syntax

`AV.AutoViz(filename="", dfte=df)`
