### ISSUE TITLE
Filename is an empty string or file not able to be loaded

### ISSUE THREAD

**Issue by delocalizer** [AutoViML/AutoViz#80]
I get this error with even the simplest csv input file
```
a,b
1,2
3,4
```
providing full path to the filename, using and specifying different separators... nothing seems to work.

**Comment by AutoViML** [comment]
@delocalizer 
Thanks for trying out AutoViz 👍 

I have tested your test csv file and it works fine . I have provided the csv file as well as the notebook for you to try it.

Just download them together and test it and let me know. I will keep this issue open until you have it resolved.

[AutoViz_test.zip](https://github.com/AutoViML/AutoViz/files/10483587/AutoViz_test.zip)

Thanks
Auto Vimal

**Comment by delocalizer** [comment]
Thanks for this. I'd like to try it out however I'm closing because I cannot pip install AutoViz in my current test environment (Python 3.11) due to wordcloud dependency https://github.com/amueller/word_cloud/issues/637.
