### ISSUE TITLE
Cannot import Box from bokeh.models 

### ISSUE THREAD

**Issue by manuelinfosec** [AutoViML/AutoViz#81]
I get this error when I try the initial import: `from autoviz.AutoViz_Class import AutoViz_Class`

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[8], line 2
      1 # from autoviz.AutoViz_Class import AutoViz_Class
----> 2 from bokeh.models import Box

ImportError: cannot import name 'Box' from 'bokeh.models' (c:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\bokeh\models\__init__.py)
```

Why?

**Comment by AutoViML** [comment]
```
"Usually this means bokeh isn't installed in the same environment as you are running, or has the wrong version. Try "import bokeh", and if that fails, install a compatible version of bokeh. If it succeeds, check bokeh. __version__ ; it presumably won't be a version compatible with your installed version of Panel."
```
That's from a simple Google Search of the problem. Try it and see.
Auto Vimal

**Comment by manuelinfosec** [comment]
Your library is super-buggy. I had to rewrite some of its dependencies and put them on PyPi for my organisation to use them. What makes you think I'd open an issue if I haven't exhausted all other options?

Please work on it further, if it's gonna scale.

**Comment by intelljames** [comment]
same problem

**Comment by satyagalla** [comment]
I am having the same kind of issue on importing the initial statement
`Warning: Duplicate qualified model declaration of 'ArrowHead'. Previous definition: <class bokeh.models.annotations.arrows.ArrowHead'>`

I installed through conda and facing same error with bokeh versions `2.4.2` and `2.4.3`

What is the solution

**Comment by AutoViML** [comment]
Hi:
There is one minor change I have made in setup.py and requirements.txt which seems to fix the problem.
In your machine, see if you can make it work by running:pip install hvplot==0.7.3 bokeh==2.4.2That seems to work and I have pushed the change as well in the latest version.Auto Vimal
    On Monday, June 5, 2023 at 11:36:56 AM EDT, Akhil Galla ***@***.***> wrote:  
 
 


I am having the same kind of issue on importing the initial statement
Warning: Duplicate qualified model declaration of 'ArrowHead'. Previous definition: <class bokeh.models.annotations.arrows.ArrowHead'>

I installed through conda and facing same error with bokeh versions 2.4.2 and 2.4.3

What is the solution
