### ISSUE TITLE
Statistically valid sample

### ISSUE THREAD

**Issue by borisRa** [AutoViML/AutoViz#82]
Hi,

I understood tat AutoViz should run statistically valid sampling ( by setting 'max_rows_analyzed')

I have found this sample [here ](https://github.com/AutoViML/AutoViz/blob/f546f13341cf13bfc0298c92662bf0a7ff40986f/autoviz/AutoViz_Utils.py#L1391):
```
dfte = dfte.sample(nrows, replace=False, random_state=99)
print('        randomly sampled %d rows from read CSV file' %nrows)
```
Which is a usual random sample (and not statistically valid)

Can you please elaborate where I can find the  statistically valid sampling code ?

Thanks,
Boris

**Comment by AutoViML** [comment]
Hi @borisRa 
Can you please explain to me what you are expecting when you say "statistically valid sample"?
Are you referring to "stratified sampling" ? In that case, I am not doing that. 
I have used random sampling and if needed, I can change it to stratified sampling. Let me know.
AutoVimal
