### ISSUE TITLE
Taking too long to execute. 

### ISSUE THREAD

**Issue by RAMahmoud** [AutoViML/AutoViz#83]
Hello,

I've tried running autoviz on several subsets of my dataset with continuous attempts failing to generate the plots. By failing, I am not referring to an error but the command executes for 5+ minutes and the plots never show.

I am sharing below a sample screenshot of the only view I end up getting as a result of running autoviz on my files.

Please let me know what other information I can provide to support. 

<img width="1095" alt="Screen Shot 2023-03-01 at 11 03 34 AM" src="https://user-images.githubusercontent.com/115408502/222080496-5478f80c-2887-4d62-9211-89dde9ef62ce.png">

A few many minutes later...
<img width="260" alt="Screen Shot 2023-03-01 at 11 32 19 AM" src="https://user-images.githubusercontent.com/115408502/222085953-06f96e59-2c5c-4b9b-8fbc-48b7a7913706.png">

**Comment by AutoViML** [comment]
I am not sure whether you have tried doing:
% matplotlib inline 

before doing AV.Autoviz command. 

In fact I have mentioned that in the READme file. Can you please double check?

thanks
Auto Vimal
