### ISSUE TITLE
UnboundLocalError: local variable 'hv_panel' referenced before assignment

### ISSUE THREAD

**Issue by hhk123** [AutoViML/AutoViz#89]
when i just run: Example 2: Visualize a Pandas DataFrame without a target variable...
I have tried version of 0.1.601, 0.1.604, but ：
```
 line 671, in draw_distplot_hv
    imgdata_list = append_panels(hv_panel, imgdata_list, chart_format)
UnboundLocalError: local variable 'hv_panel' referenced before assignment
```

**Comment by AutoViML** [comment]
try  running "pip install holoviews --upgrade"

Also you need to install the exact version numbers in the requirements.txt file.
That should fix it.
