### ISSUE TITLE
ID identification not working as expected

### ISSUE THREAD

**Issue by auguryChris** [AutoViML/AutoViz#91]
column labelled 'Id' in dataframe and the columns is found by analyze_ID_columns(). 
However, visual params list ID Columns as [] and instead Discrete string variables %s "   ['Id']"

Also it is typically better to do nomenclature matching on a forced string case such as lower() or upper()

**Comment by auguryChris** [comment]
Also it is typically better to do nomenclature matching on a forced string case such as lower() or upper()

**Comment by AutoViML** [comment]
Sometimes your Id variable may not be a unique ID variable for your rows. Hence in that case, AutoViz chooses to categorize them as discrete_string_vars. This is part of a very complicated logic that I use. If you want to fix it, you can post a PR and I can take a look. Sorry

Auto Vimal
