### ISSUE TITLE
How can we make this usable for the simple python script. Can we remove the ipython dependency.

### ISSUE THREAD

**Issue by Vinayakmoudgil** [AutoViML/AutoViz#93]

**Comment by AutoViML** [comment]
Hello: thanks for reaching out.
Is there an ipython dependency? If so, can you provide some more details?I don't see any dependency.ThanksAuto Vimal

**Comment by AutoViML** [comment]
Hi @Vinayakmoudgil 👍 
Thanks for testing AutoViz.
I have removed all ipython dependencies. Can you please upgrade your autoviz version to the latest and confirm?
Thanks
Auto Vimal

**Comment by Vinayakmoudgil** [comment]
Sure I will give it a try and get back to you.
