### ISSUE TITLE
Exception has occurred: OSError X

### ISSUE THREAD

**Issue by HKEdwin22** [AutoViML/AutoViz#94]
Hi, this error occurs when the script imports Autoviz_Class from autoviz. The detail is as below:

Exception has occurred: OSError X
'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'

The two packages have been installed under the same directory "\anaconda3\envs\Kaggle_Competition\Lib\site-packages". 

More details:
autoviz version: 0.1.720
seaborn version: 0.12.2

Anything I could do to solve this? Thanks in advance.

**Comment by AutoViML** [comment]
It is extremely hard to troubleshoot conda environments. I am sorry you need to Google search for solutions.Thanks,Auto Vimal    On Sunday, October 1, 2023 at 09:11:14 AM EDT, Edwin Hui ***@***.***> wrote:  
 
 


Hi, this error occurs when the script imports Autoviz_Class from autoviz. The detail is as below:

Exception has occurred: OSError X
'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in style.available)
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn'

The two packages have been installed under the same directory "\anaconda3\envs\Kaggle_Competition\Lib\site-packages".

More details:
autoviz version: 0.1.720
seaborn version: 0.12.2

Anything I could do to solve this? Thanks in advance.
