### ISSUE TITLE
Autoviz library gives List Index Out of Range

### ISSUE THREAD

**Issue by ankita2020** [AutoViML/AutoViz#96]
dataset has 200 rows and columns(5 string columns,2 Integer columns,1 datetime column).
I have select target column has 2 unique values(1,4).
then I created the charts and autoviz library gave an error "List Index out of range

Shape of your Data Set loaded: (200, 8)
#######################################################################################
#######################################################################################
Classifying variables in data set...
  Printing upto 30 columns max in each category:
    Numeric Columns : []
    Integer-Categorical Columns: []
    String-Categorical Columns: ['Affected__by', 'Period', 'Pct__of__Colonies__Impacted']
    Factor-Categorical Columns: []
    String-Boolean Columns: ['State', 'state_code']
    Numeric-Boolean Columns: []
    Discrete String Columns: []
    NLP text Columns: []
    Date Time Columns: ['Year']
    ID Columns: []
    Columns that will not be considered in modeling: ['Program']
    7 Predictors classified...
        1 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['Program']

################ Binary_Classification problem #####################
   Columns to delete:
"   ['Program']"
   Boolean variables %s
"   ['State', 'state_code']"
   Categorical variables %s
("   ['Affected__by', 'Period', 'Pct__of__Colonies__Impacted', 'State', "
 "'state_code']")
   Continuous variables %s
'   []'
   Discrete string variables %s
'   []'
   Date and time variables %s
"   ['Year']"
   ID variables %s
'   []'
   Target variable %s
'   ANSI'
Saving distplots_cats in HTML format
Saving kde_plots in HTML format
modeltype Binary_Classification
Traceback (most recent call last):
  File "auto.py", line 18, in <module>
    dft = AV.AutoViz(
  File "D:\Download\plots\final\autoviz\AutoViz_Class.py", line 257, in AutoViz
    dft = AutoViz_Holo(filename, sep, depVar, dfte, header, verbose,
  File "D:\Download\plots\final\autoviz\AutoViz_Holo.py", line 198, in AutoViz_Holo
    drawobj7 = draw_date_vars_hv(dfin,dep,date_vars, nums, chart_format, problem_type, mk_dir, verbose,add_extra)    
  File "D:\Download\plots\final\autoviz\AutoViz_Holo.py", line 951, in draw_date_vars_hv
    print('quantile',quantileable[0])
IndexError: list index out of range

**Comment by AutoViML** [comment]
Hi @ankita2020 👍 
Thanks for pointing this out. AutoViz should have seen that your dataset has no continuous or datetime vars and should have stopped plotting those. I am now adding a check. Hope it fixes it. Please upgrade your autoviz version to the latest and check.
Thanks
Auto Vimal
