### ISSUE TITLE
Seabon style in Matplotlib being deprecated

### ISSUE THREAD

**Issue by thewchan** [AutoViML/AutoViz#99]
Hi just wanted to check which Matplotlib version is being supported? The requirements in `setup.py` says `>=3.3.3`, but "seaborn" style which is set when importing AutoViz_Class tries to set the style to seaborn was deprecated since matplotlib 3.6 (see: https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed)

The error message I got was: `https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#seaborn-styles-renamed`

**Comment by AutoViML** [comment]
Hi @thewchan 👍 
Thanks for the catch! I have updated the setup.py and requirements.txt to put a range in matplotlib versions as follows:
```
matplotlib>=3.3.3, <3.6
```
Hope this helps,
let me now
Auto Vimal
